services:
  - type: web
    name: greenway-telegram-bot
    env: python
    plan: free
    region: singapore
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers=1 --bind 0.0.0.0:$PORT"
    autoDeploy: true

    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
